### ISSUE TITLE
Random Number for User Session

### ISSUE THREAD

**Issue by cdesch** [Vasiliauskas/Gappalytics#5]
Can the `userRandomNumber` associated with the 

        public AnalyticsSession(string domain, string trackingCode, int userRandomNumber, int visitCount, DateTime? firstVisitTimeStamp)

be used as the User's Id instead?

**Comment by Vasiliauskas** [comment]
It can, but it will affect the sessions state if you for instance close app and run it again with same number it will be treated as same session if not timed out.

**Comment by cdesch** [comment]
Okay. Is there a way to track the user with each session?

**Comment by Vasiliauskas** [comment]
That is a question I have no answer yet. I would suggest reading up at google api docs: https://support.google.com/analytics/answer/3123662?hl=en also, feel free to do a pull request if changes are needed to the lib

**Comment by cdesch** [comment]
I'll see what I can do as I try leveraging the library. Thank you @Vasiliauskas
